### ISSUE TITLE
Fix translations system for add-ons

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/addon-store-submission#5]
I tried to create an issue in mrConfig without success (not sure if they are disabled).
Many notifications are sent from Exbi server about mr commands not working. This should be fixed if possible.
Alternatively, it maybe announced that add-on maintainers should take care about translations (and or also regarding other questions) independently without depending on a central system.
BTW: This is done ia a project about which I was informed recently, where each person can publish plugins in pip repository without requiring to pass a review process, and the program has an option to install a plugin manager. Alternatively plugins can be installed from command line via pip, but the fact is that they can be included in the program directly without a central system. I think that two approaches are valid, and maybe good for developers to know what they should do:

https://github.com/openstenoproject/plover/wiki/Plugins

**Comment by feerrenrut** [comment]
Thanks @nvdaes Issues have now been enabled on mrconfig.

**Comment by feerrenrut** [comment]
I'll close this issue, since it looks like it is replaced by: #3
